apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: repo-33-dev-pipeline
  namespace: repo-33
spec:
  pipelineRef:
    name: dev-pipeline
  params:
  - name: REVISION
    value: main
  - name: BUILD_COMMAND
    value: |
      make build
  - name: TEST_IMAGE_NAME
    value: "harbor.bluzin.io/library/ginkgo"
  - name: GOCACHE
    value: "/go/.cache"
  - name: CODE_REPO_URL
    value: "ssh://git@gitlab.bluzin.io:2222/nautes-labs/api-server.git"
  - name: SONAQUBE_HOST
    value: "http://10.204.118.216:32183"
  - name: SONAQUBE_KEY
    value: "api-server"
  - name: SONAQUBE_TOKEN
    value: "sqp_e290c256b2b8ff45a95eaade2399af55137b8ecc"
  taskRunSpecs:
  - pipelineTaskName: git-clone
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/tls-secret: "ca"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: 'repo-33'
        vault.hashicorp.com/agent-run-as-user: '0' 
        vault.hashicorp.com/agent-run-as-group: '0'
        vault.hashicorp.com/agent-inject-secret-id_ecdsa: "git/data/gitlab/repo-33/default/readwrite"
        vault.hashicorp.com/secret-volume-path-id_ecdsa: "/root/.ssh"
        vault.hashicorp.com/agent-inject-perms-id_ecdsa: '0400'
        vault.hashicorp.com/agent-inject-template-id_ecdsa: |
          {{- with secret "git/data/gitlab/repo-33/default/readwrite" -}}
          {{ .Data.data.deploykey }}
          {{- end -}}

  - pipelineTaskName: go-pull-dependency
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/tls-secret: "ca"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: 'repo-33'
        vault.hashicorp.com/agent-run-as-user: '0' 
        vault.hashicorp.com/agent-run-as-group: '0'
        vault.hashicorp.com/agent-inject-secret-gitlab_ca.crt: "pki/data/default"
        vault.hashicorp.com/secret-volume-path-gitlab_ca.crt: "/usr/local/share/ca-certificates"
        vault.hashicorp.com/agent-inject-perms-gitlab_ca.crt: '0400'
        vault.hashicorp.com/agent-inject-template-gitlab_ca.crt: |
          {{- with secret "pki/data/default" -}}
          {{ .Data.data.cacert }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-id_ecdsa: "git/data/gitlab/repo-33/default/readwrite"
        vault.hashicorp.com/secret-volume-path-id_ecdsa: "/root/.ssh"
        vault.hashicorp.com/agent-inject-perms-id_ecdsa: '0400'
        vault.hashicorp.com/agent-inject-template-id_ecdsa: |
          {{- with secret "git/data/gitlab/repo-33/default/readwrite" -}}
          {{ .Data.data.deploykey }}
          {{- end -}}

  - pipelineTaskName: go-test
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/tls-secret: "ca"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: 'repo-33'
        vault.hashicorp.com/agent-run-as-user: '0' 
        vault.hashicorp.com/agent-run-as-group: '0'
        vault.hashicorp.com/agent-inject-secret-gitlab_ca.crt: "pki/data/default"
        vault.hashicorp.com/secret-volume-path-gitlab_ca.crt: "/usr/local/share/ca-certificates"
        vault.hashicorp.com/agent-inject-perms-gitlab_ca.crt: '0400'
        vault.hashicorp.com/agent-inject-template-gitlab_ca.crt: |
          {{- with secret "pki/data/default" -}}
          {{ .Data.data.cacert }}
          {{- end -}}
        vault.hashicorp.com/agent-inject-secret-id_ecdsa: "git/data/gitlab/repo-33/default/readwrite"
        vault.hashicorp.com/secret-volume-path-id_ecdsa: "/root/.ssh"
        vault.hashicorp.com/agent-inject-perms-id_ecdsa: '0400'
        vault.hashicorp.com/agent-inject-template-id_ecdsa: |
          {{- with secret "git/data/gitlab/repo-33/default/readwrite" -}}
          {{ .Data.data.deploykey }}
          {{- end -}}  


  workspaces:
  - name: source-volume
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500M
  - name: go-path
    persistentVolumeClaim:
      claimName: go-tmp
  - name: sonar-settings
    emptyDir: {}
